### PR TITLE
Http motion

### PR DESCRIPTION
**Pull request by flipit**
Tested locally now, can't guarantee it's the best code but I've tried to follow examples and standards and keep it lightweight and simple. Happy take advise.

### CODE REVIEW

**Comment by Sunoo** [comment]
It's building this time, so that's good. I'll probably be able to review and test this code tonight.

One thing I did notice is can you please remove the `.DS_Store` file from this pull request?

**Comment by Sunoo** [comment]
@flipit Okay, I've done some testing, and I'm not ready to accept the pull in its current state.

The biggest issue I've seen is that there is no error handling. If you go to `http://hostname:5555/` it will immediate crash Homebridge:
```
[7/11/2020, 7:02:12 PM] [Camera-ffmpeg] http request recieved
[7/11/2020, 7:02:12 PM] TypeError: Cannot read property '1' of undefined
    at IncomingMessage.<anonymous> (/home/pi/httpmotion/src/index.ts:271:46)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

But also, this should support resetting the motion alerts as well as just triggering them.

I do see the value in this idea though, and if you wanted, I could make the changes needed to accept it myself. I don't want to just jump in and step on your toes by doing that though, so let me know.

**Comment by flipit** [comment]
@Sunoo I'm more then happy for someone that knows what they're doing to step in ;-) TypeScript/Java Script is all new to me. TBH. I have no idea how to remove  the .DS_Store file from the pull request. Something I'll go reseach.
Thanks

**Comment by Sunoo** [comment]
Okay, I’ll pull your code into another fork and fix it up there then.

**Comment by RomeyRome206** [comment]
Did this ever get pulled in elsewhere? 

I haven’t updated this plugin in forever because I had http motion listener hacked into it (basically combined this & http-motion plugin). Then I have a separate service monitoring the NVR for alerts, and triggering it via HTTP.

**Comment by Sunoo** [comment]
@RomeyRome206 Yep! https://sunoo.github.io/homebridge-camera-ffmpeg/automation/http.html

**Pull request closed without merging**
