### PR TITLE
Http motion

### PR DESCRIPTION
**Pull request by flipit**
Added: Trigger motion sensor by HTTP #609

### CODE REVIEW

**Comment by donavanbecker** [comment]
@normen and @Sunoo thoughts?

**Comment by Sunoo** [comment]
This code fails to build in its current state, so clearly has not been tested at all. Developers really need to test things themselves before submitting a pull request for it.

While I'm against trying to support every possible protocol and variation, and think secondary plugins to do translation are largely the way to go, I'm not necessarily against HTTP motion support, since it requires no external setup, unlike MQTT. However, it would have to be implemented cleanly, and most importantly, actually work.

**Comment by normen** [comment]
Also why has this only been added for the motion detection anyway? It would work for the doorbell as well ^^

**Comment by flipit** [comment]
Hello. Thanks for the comments. In my rush to learn TypeScript and NodeJS and re-familiarize myself with Git. I pushed a very early version, that wasn't tested. Sorry that wasn't my intent.  I now have a tested working version, I've tried to ensure it aligns with the existing code and is a simple addition. It leverages the same handler for mqtt, so it does support Doorbell and Motion.  If you'd like me to resubmit the pull request. I think I can now do that.  I wrote this for myself, but I saw some folks asking for support so I thought I'd share.

**Comment by Sunoo** [comment]
No worries, go ahead and submit a new pull request and I’ll take a look at it soon.

**Pull request closed without merging**
