### PR TITLE
Add MQTT support for Motion Detect

### PR DESCRIPTION
**Pull request by donavanbecker**
@fennec622, I created this PR so we can close the other one. 

Let me know once this is ready for testing.

### CODE REVIEW

**Comment by donavanbecker** [comment]
Just publish to topic, no message, `homebridge/motion/Camera_name`.
You must add `_`  to your camera if you have space in the name.

```
{
  "platform": "Camera-ffmpeg",
  "mqtt": "127.0.0.1",
  "topics": "homebridge/motion/#",
  "cameras": [
    {
      "name": "Camera name",
      "motion": true,
      "videoConfig": {
        "source": "-re -i http://10.0.0.1",
        "stillImageSource": "-i http://10.0.0.1",
        "maxStreams": 5,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 15,
        "maxBitrate": 1000
      }
    }
  ]
}
```

**Comment by fennec622** [comment]
Thanks
Sorry don't have time for the moment

**Comment by fennec622** [comment]
I make new Pull request with adaptation for typescript

**Comment by donavanbecker** [comment]
> I make new Pull request with adaptation for typescript

you are going too?

**Comment by fennec622** [comment]
yes it's ok

**Pull request closed without merging**
