### PR TITLE
Add MQTT support for Motion Detect

### PR DESCRIPTION
**Pull request by fennec622**
Just publish to topic, no message, `homebridge/motion/Camera_name`.
You must add `_`  to your camera if you have space in the name.

```
{
  "platform": "Camera-ffmpeg",
  "mqtt": "127.0.0.1",
  "topics": "homebridge/motion/#",
  "cameras": [
    {
      "name": "Camera name",
      "motion": true,
      "videoConfig": {
        "source": "-re -i http://10.0.0.1",
        "stillImageSource": "-i http://10.0.0.1",
        "maxStreams": 5,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 15,
        "maxBitrate": 1000
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by donavanbecker** [comment]
See #527, you will want to incorporate this into the breaking changes there to get merged.

**Comment by donavanbecker** [comment]
@fennec622 Would you mind fixing this for the `beta` branch? I would gladly merge after that!

**Comment by fennec622** [comment]
I try to make that this night 
Thanks

**Comment by donavanbecker** [comment]
> I try to make that this night
> Thanks

Awesome! I have released `v2.0.0`. Once you are done we can release v2.1.0

**Pull request closed without merging**
