### PR TITLE
Remove Underscore to Space Replacement in MQTT Code

### PR DESCRIPTION
**Pull request by Sunoo**
This is a fix to the underscore to space replacement in the MQTT messages.

In Javascript, string.replace only works on the first instance of the pattern found unless regular expressions are used.

### CODE REVIEW

**Comment by Sunoo** [comment]
Looks like #605 is basically doing what this is doing at this point, so closing now.

**Comment by Sunoo** [comment]
I'm working on a new pull request right now to add resetting the motion sensor from MQTT right now, should be opening it soon.

**Comment by Sunoo** [comment]
@donavanbecker As mentioned earlier, I've opened pull request #606

**Comment by donavanbecker** [comment]
Merged! Thanks

**Pull request closed without merging**
