### PR TITLE
v2.2.1

### PR DESCRIPTION
**Pull request by donavanbecker**
### Changes
  
  * Update Dependencies.

### CODE REVIEW

**Comment by donavanbecker** [comment]
@fennec622 any issues with updating the mqtt dependency to `4.1.0`?

**Comment by donavanbecker** [comment]
@california444 and @Sunoo, any issues with these dependency updates?

**Comment by Sunoo** [comment]
There shouldn’t be, give me a few and I’ll get this installed on my test instance and confirm that.

**Comment by Sunoo** [comment]
@donavanbecker The MQTT stuff seems to be working fine with the new dependency there.

However, and this may be just some weirdness on my test system, I had to manually `npm i @types/node` to get this version to build. I don't remember needing to do that on the previous version.

**Comment by donavanbecker** [comment]
@Sunoo Is this something we need to add to the package.json script?

**Comment by Sunoo** [comment]
@donavanbecker It's already there, so I'm not sure why my system didn't pull it down: https://github.com/homebridge-plugins/homebridge-camera-ffmpeg/blob/e24d4dd2e28fa0ce6daab45f617aceaea1b76a10/package.json#L48

**Comment by donavanbecker** [comment]
Weird

**Comment by Sunoo** [comment]
Yea, given that the builds seem to be passing on GitHub, I'm just gonna assume it's some weirdness with my test device and say it's safe to ignore it.

**Pull request merged**
